ENGINE_REDIS_ADDR=localhost:6379
ENGINE_REDIS_PASSWORD=
ENGINE_REDIS_DB=0
ENGINE_CACHE_SIZE=1024
FLOW_REDIS_ADDR=localhost:6379
FLOW_REDIS_PASSWORD=
FLOW_REDIS_DB=0
FLOW_CACHE_SIZE=10240
API_PORT=8080
API_HOST=0.0.0.0
WEBHOOK_BASE_URL=http://localhost:8080
DEV_MODE=true
LOG_LEVEL=info

go run cmd/spuds/main.go
