CATALOG_REDIS_ADDR=localhost:6379
CATALOG_REDIS_PASSWORD=
CATALOG_REDIS_DB=0
PARTITION_REDIS_ADDR=localhost:6379
PARTITION_REDIS_PASSWORD=
PARTITION_REDIS_DB=0
API_PORT=8080
API_HOST=0.0.0.0
WEBHOOK_BASE_URL=http://localhost:8080
DEV_MODE=true
LOG_LEVEL=info

go run cmd/argyll/main.go
