/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  corePlugins: {
    backgroundColor: false,
    textColor: false,
    borderColor: false,
    margin: false,
    padding: false,
    gap: false,
    borderRadius: false,
    borderWidth: false,
    fontSize: false,
    fontWeight: false,
    flexbox: false,
    flexDirection: false,
    flex: false,
    flexGrow: false,
    flexShrink: false,
    alignItems: false,
    justifyContent: false,
    width: false,
    height: false,
    minWidth: false,
    maxWidth: false,
    minHeight: false,
    maxHeight: false,
  },
  plugins: [],
};
